"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ICharacterStorage__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "worldId",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
            {
                internalType: "uint256[]",
                name: "itemDefinitionIds",
                type: "uint256[]",
            },
        ],
        name: "getItems",
        outputs: [
            {
                internalType: "int64[]",
                name: "",
                type: "int64[]",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
class ICharacterStorage__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.ICharacterStorage__factory = ICharacterStorage__factory;
ICharacterStorage__factory.abi = _abi;
