"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ICharacterEquipment__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "worldId",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256[]",
                name: "itemIds",
                type: "uint256[]",
            },
        ],
        name: "Equip",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "worldId",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
            {
                internalType: "uint256[]",
                name: "itemDefinitionIds",
                type: "uint256[]",
            },
        ],
        name: "equip",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "worldId",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
        ],
        name: "getEquipments",
        outputs: [
            {
                internalType: "uint256[]",
                name: "",
                type: "uint256[]",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "worldId",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
            {
                internalType: "uint256[]",
                name: "itemDefinitionIds",
                type: "uint256[]",
            },
        ],
        name: "validateEquip",
        outputs: [
            {
                components: [
                    {
                        internalType: "bool",
                        name: "validWorldId",
                        type: "bool",
                    },
                    {
                        internalType: "bool",
                        name: "validTokenId",
                        type: "bool",
                    },
                    {
                        internalType: "bool",
                        name: "validItemDefinitionIdLength",
                        type: "bool",
                    },
                    {
                        internalType: "bool[]",
                        name: "validSlots",
                        type: "bool[]",
                    },
                    {
                        internalType: "bool[]",
                        name: "validItemDefinitionIds",
                        type: "bool[]",
                    },
                    {
                        internalType: "bool[]",
                        name: "equipableItems",
                        type: "bool[]",
                    },
                    {
                        internalType: "bool[]",
                        name: "validItemCounts",
                        type: "bool[]",
                    },
                ],
                internalType: "struct ICharacterEquipment.EquipValidationResult",
                name: "",
                type: "tuple",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
class ICharacterEquipment__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.ICharacterEquipment__factory = ICharacterEquipment__factory;
ICharacterEquipment__factory.abi = _abi;
