"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ICharacterReveal__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "worldId",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "characterDefinitionId",
                type: "uint256",
            },
        ],
        name: "Reveal",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "worldId",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
        ],
        name: "getRevealState",
        outputs: [
            {
                components: [
                    {
                        internalType: "uint256",
                        name: "characterDefinitionId",
                        type: "uint256",
                    },
                    {
                        internalType: "bool",
                        name: "isRevealed",
                        type: "bool",
                    },
                ],
                internalType: "struct ICharacterReveal.RevealStateRecord",
                name: "",
                type: "tuple",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "worldId",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
        ],
        name: "reveal",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class ICharacterReveal__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.ICharacterReveal__factory = ICharacterReveal__factory;
ICharacterReveal__factory.abi = _abi;
