"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IItemPackReveal__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: true,
                internalType: "uint256",
                name: "worldId",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
            {
                indexed: true,
                internalType: "uint256",
                name: "itemPackId",
                type: "uint256",
            },
            {
                indexed: false,
                internalType: "uint256[]",
                name: "itemDefinitionIds",
                type: "uint256[]",
            },
            {
                indexed: false,
                internalType: "int64[]",
                name: "amounts",
                type: "int64[]",
            },
        ],
        name: "RevealItemPack",
        type: "event",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "playerWallet",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "worldId",
                type: "uint256",
            },
        ],
        name: "getItemPacks",
        outputs: [
            {
                components: [
                    {
                        internalType: "uint256",
                        name: "itemPackId",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "itemPackDefinitionId",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "tokenId",
                        type: "uint256",
                    },
                ],
                internalType: "struct IItemPackReveal.ItemPackRecord[]",
                name: "",
                type: "tuple[]",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "playerWallet",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "worldId",
                type: "uint256",
            },
        ],
        name: "getItemPacksAssociatedWithNFT",
        outputs: [
            {
                components: [
                    {
                        internalType: "uint256",
                        name: "itemPackId",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "itemPackDefinitionId",
                        type: "uint256",
                    },
                    {
                        internalType: "uint256",
                        name: "tokenId",
                        type: "uint256",
                    },
                ],
                internalType: "struct IItemPackReveal.ItemPackRecord[]",
                name: "",
                type: "tuple[]",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "worldId",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "itemPackId",
                type: "uint256",
            },
        ],
        name: "isRevealed",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "worldId",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "itemPackId",
                type: "uint256",
            },
        ],
        name: "reveal",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class IItemPackReveal__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IItemPackReveal__factory = IItemPackReveal__factory;
IItemPackReveal__factory.abi = _abi;
