/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IItemAcquisitionHistory,
  IItemAcquisitionHistoryInterface,
} from "../../../contracts/interfaces/IItemAcquisitionHistory";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "worldId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "itemDefinitionIds",
        type: "uint256[]",
      },
    ],
    name: "getLastAcquisitionTimestamps",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IItemAcquisitionHistory__factory {
  static readonly abi = _abi;
  static createInterface(): IItemAcquisitionHistoryInterface {
    return new utils.Interface(_abi) as IItemAcquisitionHistoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IItemAcquisitionHistory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IItemAcquisitionHistory;
  }
}
