"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.IWorldStore__factory = exports.IWorld__factory = exports.IItemTransfer__factory = exports.IItemPackReveal__factory = exports.IItemExchange__factory = exports.IItemAcquisitionHistory__factory = exports.IGameAccess__factory = exports.IEventCheckin__factory = exports.ICharacterStorage__factory = exports.ICharacterReveal__factory = exports.ICharacterEquipment__factory = exports.token = exports.erc = exports.definitions = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.definitions = __importStar(require("./definitions"));
exports.erc = __importStar(require("./erc"));
exports.token = __importStar(require("./token"));
var ICharacterEquipment__factory_1 = require("./ICharacterEquipment__factory");
Object.defineProperty(exports, "ICharacterEquipment__factory", { enumerable: true, get: function () { return ICharacterEquipment__factory_1.ICharacterEquipment__factory; } });
var ICharacterReveal__factory_1 = require("./ICharacterReveal__factory");
Object.defineProperty(exports, "ICharacterReveal__factory", { enumerable: true, get: function () { return ICharacterReveal__factory_1.ICharacterReveal__factory; } });
var ICharacterStorage__factory_1 = require("./ICharacterStorage__factory");
Object.defineProperty(exports, "ICharacterStorage__factory", { enumerable: true, get: function () { return ICharacterStorage__factory_1.ICharacterStorage__factory; } });
var IEventCheckin__factory_1 = require("./IEventCheckin__factory");
Object.defineProperty(exports, "IEventCheckin__factory", { enumerable: true, get: function () { return IEventCheckin__factory_1.IEventCheckin__factory; } });
var IGameAccess__factory_1 = require("./IGameAccess__factory");
Object.defineProperty(exports, "IGameAccess__factory", { enumerable: true, get: function () { return IGameAccess__factory_1.IGameAccess__factory; } });
var IItemAcquisitionHistory__factory_1 = require("./IItemAcquisitionHistory__factory");
Object.defineProperty(exports, "IItemAcquisitionHistory__factory", { enumerable: true, get: function () { return IItemAcquisitionHistory__factory_1.IItemAcquisitionHistory__factory; } });
var IItemExchange__factory_1 = require("./IItemExchange__factory");
Object.defineProperty(exports, "IItemExchange__factory", { enumerable: true, get: function () { return IItemExchange__factory_1.IItemExchange__factory; } });
var IItemPackReveal__factory_1 = require("./IItemPackReveal__factory");
Object.defineProperty(exports, "IItemPackReveal__factory", { enumerable: true, get: function () { return IItemPackReveal__factory_1.IItemPackReveal__factory; } });
var IItemTransfer__factory_1 = require("./IItemTransfer__factory");
Object.defineProperty(exports, "IItemTransfer__factory", { enumerable: true, get: function () { return IItemTransfer__factory_1.IItemTransfer__factory; } });
var IWorld__factory_1 = require("./IWorld__factory");
Object.defineProperty(exports, "IWorld__factory", { enumerable: true, get: function () { return IWorld__factory_1.IWorld__factory; } });
var IWorldStore__factory_1 = require("./IWorldStore__factory");
Object.defineProperty(exports, "IWorldStore__factory", { enumerable: true, get: function () { return IWorldStore__factory_1.IWorldStore__factory; } });
