/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWorld,
  IWorldInterface,
} from "../../../contracts/interfaces/IWorld";

const _abi = [
  {
    inputs: [],
    name: "getItemPackNFTs",
    outputs: [
      {
        internalType: "contract IItemPackNFT[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getL1NFT",
    outputs: [
      {
        internalType: "contract IL1NFT",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "game_",
        type: "address",
      },
    ],
    name: "setGame",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWorld__factory {
  static readonly abi = _abi;
  static createInterface(): IWorldInterface {
    return new Interface(_abi) as IWorldInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IWorld {
    return new Contract(address, _abi, runner) as unknown as IWorld;
  }
}
