/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IMintManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getBalanceBySeries"
      | "getMintedCount"
      | "getMintedCountBySeries"
      | "getSeriesIdByTokenId"
      | "mintBySeries"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getBalanceBySeries",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMintedCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMintedCountBySeries",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSeriesIdByTokenId",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBySeries",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getBalanceBySeries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMintedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMintedCountBySeries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSeriesIdByTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintBySeries",
    data: BytesLike
  ): Result;
}

export interface IMintManager extends BaseContract {
  connect(runner?: ContractRunner | null): IMintManager;
  waitForDeployment(): Promise<this>;

  interface: IMintManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getBalanceBySeries: TypedContractMethod<
    [user: AddressLike, worldId: BigNumberish, seriesId: BigNumberish],
    [bigint],
    "view"
  >;

  getMintedCount: TypedContractMethod<
    [worldId: BigNumberish],
    [bigint],
    "view"
  >;

  getMintedCountBySeries: TypedContractMethod<
    [worldId: BigNumberish, seriesId: BigNumberish],
    [bigint],
    "view"
  >;

  getSeriesIdByTokenId: TypedContractMethod<
    [worldId: BigNumberish, tokenId: BigNumberish],
    [bigint],
    "view"
  >;

  mintBySeries: TypedContractMethod<
    [
      to: AddressLike,
      quantity: BigNumberish,
      worldId: BigNumberish,
      seriesId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getBalanceBySeries"
  ): TypedContractMethod<
    [user: AddressLike, worldId: BigNumberish, seriesId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMintedCount"
  ): TypedContractMethod<[worldId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMintedCountBySeries"
  ): TypedContractMethod<
    [worldId: BigNumberish, seriesId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSeriesIdByTokenId"
  ): TypedContractMethod<
    [worldId: BigNumberish, tokenId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintBySeries"
  ): TypedContractMethod<
    [
      to: AddressLike,
      quantity: BigNumberish,
      worldId: BigNumberish,
      seriesId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
