/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace ICharacterEquipment {
  export type EquipValidationResultStruct = {
    validWorldId: PromiseOrValue<boolean>;
    validTokenId: PromiseOrValue<boolean>;
    validItemDefinitionIdLength: PromiseOrValue<boolean>;
    validSlots: PromiseOrValue<boolean>[];
    validItemDefinitionIds: PromiseOrValue<boolean>[];
    equipableItems: PromiseOrValue<boolean>[];
    validItemCounts: PromiseOrValue<boolean>[];
  };

  export type EquipValidationResultStructOutput = [
    boolean,
    boolean,
    boolean,
    boolean[],
    boolean[],
    boolean[],
    boolean[]
  ] & {
    validWorldId: boolean;
    validTokenId: boolean;
    validItemDefinitionIdLength: boolean;
    validSlots: boolean[];
    validItemDefinitionIds: boolean[];
    equipableItems: boolean[];
    validItemCounts: boolean[];
  };
}

export interface ICharacterEquipmentInterface extends utils.Interface {
  functions: {
    "equip(uint256,uint256,uint256[])": FunctionFragment;
    "getEquipments(uint256,uint256)": FunctionFragment;
    "validateEquip(uint256,uint256,uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "equip" | "getEquipments" | "validateEquip"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "equip",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getEquipments",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "validateEquip",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "equip", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEquipments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateEquip",
    data: BytesLike
  ): Result;

  events: {
    "Equip(uint256,uint256,uint256[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Equip"): EventFragment;
}

export interface EquipEventObject {
  worldId: BigNumber;
  tokenId: BigNumber;
  itemIds: BigNumber[];
}
export type EquipEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber[]],
  EquipEventObject
>;

export type EquipEventFilter = TypedEventFilter<EquipEvent>;

export interface ICharacterEquipment extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ICharacterEquipmentInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    equip(
      worldId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      itemDefinitionIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getEquipments(
      worldId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    validateEquip(
      worldId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      itemDefinitionIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[ICharacterEquipment.EquipValidationResultStructOutput]>;
  };

  equip(
    worldId: PromiseOrValue<BigNumberish>,
    tokenId: PromiseOrValue<BigNumberish>,
    itemDefinitionIds: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getEquipments(
    worldId: PromiseOrValue<BigNumberish>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  validateEquip(
    worldId: PromiseOrValue<BigNumberish>,
    tokenId: PromiseOrValue<BigNumberish>,
    itemDefinitionIds: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<ICharacterEquipment.EquipValidationResultStructOutput>;

  callStatic: {
    equip(
      worldId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      itemDefinitionIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    getEquipments(
      worldId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    validateEquip(
      worldId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      itemDefinitionIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<ICharacterEquipment.EquipValidationResultStructOutput>;
  };

  filters: {
    "Equip(uint256,uint256,uint256[])"(
      worldId?: PromiseOrValue<BigNumberish> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      itemIds?: null
    ): EquipEventFilter;
    Equip(
      worldId?: PromiseOrValue<BigNumberish> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      itemIds?: null
    ): EquipEventFilter;
  };

  estimateGas: {
    equip(
      worldId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      itemDefinitionIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getEquipments(
      worldId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateEquip(
      worldId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      itemDefinitionIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    equip(
      worldId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      itemDefinitionIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getEquipments(
      worldId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateEquip(
      worldId: PromiseOrValue<BigNumberish>,
      tokenId: PromiseOrValue<BigNumberish>,
      itemDefinitionIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
