/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IItemAcquisitionHistoryInterface extends Interface {
  getFunction(
    nameOrSignature: "getLastAcquisitionTimestamps"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getLastAcquisitionTimestamps",
    values: [BigNumberish, BigNumberish, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLastAcquisitionTimestamps",
    data: BytesLike
  ): Result;
}

export interface IItemAcquisitionHistory extends BaseContract {
  connect(runner?: ContractRunner | null): IItemAcquisitionHistory;
  waitForDeployment(): Promise<this>;

  interface: IItemAcquisitionHistoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLastAcquisitionTimestamps: TypedContractMethod<
    [
      worldId: BigNumberish,
      tokenId: BigNumberish,
      itemDefinitionIds: BigNumberish[]
    ],
    [bigint[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLastAcquisitionTimestamps"
  ): TypedContractMethod<
    [
      worldId: BigNumberish,
      tokenId: BigNumberish,
      itemDefinitionIds: BigNumberish[]
    ],
    [bigint[]],
    "view"
  >;

  filters: {};
}
