/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IWorldInterface extends utils.Interface {
  functions: {
    "getItemPackNFTs()": FunctionFragment;
    "getL1NFT()": FunctionFragment;
    "setGame(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getItemPackNFTs" | "getL1NFT" | "setGame"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getItemPackNFTs",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getL1NFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setGame",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "getItemPackNFTs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getL1NFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setGame", data: BytesLike): Result;

  events: {};
}

export interface IWorld extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IWorldInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getItemPackNFTs(overrides?: CallOverrides): Promise<[string[]]>;

    getL1NFT(overrides?: CallOverrides): Promise<[string]>;

    setGame(
      game_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getItemPackNFTs(overrides?: CallOverrides): Promise<string[]>;

  getL1NFT(overrides?: CallOverrides): Promise<string>;

  setGame(
    game_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getItemPackNFTs(overrides?: CallOverrides): Promise<string[]>;

    getL1NFT(overrides?: CallOverrides): Promise<string>;

    setGame(
      game_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getItemPackNFTs(overrides?: CallOverrides): Promise<BigNumber>;

    getL1NFT(overrides?: CallOverrides): Promise<BigNumber>;

    setGame(
      game_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getItemPackNFTs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getL1NFT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setGame(
      game_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
