"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IERC4906__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IERC4906__factory_1 = require("./IERC4906__factory");
Object.defineProperty(exports, "IERC4906__factory", { enumerable: true, get: function () { return IERC4906__factory_1.IERC4906__factory; } });
