/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IItemDefinition,
  IItemDefinitionInterface,
} from "../../../contracts/definitions/IItemDefinition";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "itemDefinitionId_",
        type: "uint256",
      },
    ],
    name: "getDefinition",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "itemDefinitionId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "category",
            type: "string",
          },
          {
            internalType: "bool",
            name: "enable",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "salable",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "transferable",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "effectivePeriod",
            type: "uint256",
          },
        ],
        internalType: "struct IItemDefinition.ItemDefinitionRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "itemDefinitionId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "category",
            type: "string",
          },
          {
            internalType: "bool",
            name: "enable",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "salable",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "transferable",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "effectivePeriod",
            type: "uint256",
          },
        ],
        internalType: "struct IItemDefinition.ItemDefinitionRecord[]",
        name: "records",
        type: "tuple[]",
      },
    ],
    name: "setDefinitions",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IItemDefinition__factory {
  static readonly abi = _abi;
  static createInterface(): IItemDefinitionInterface {
    return new Interface(_abi) as IItemDefinitionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IItemDefinition {
    return new Contract(address, _abi, runner) as unknown as IItemDefinition;
  }
}
