/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IWorldInterface extends Interface {
  getFunction(
    nameOrSignature: "getItemPackNFTs" | "getL1NFT" | "setGame"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getItemPackNFTs",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getL1NFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setGame",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getItemPackNFTs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getL1NFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setGame", data: BytesLike): Result;
}

export interface IWorld extends BaseContract {
  connect(runner?: ContractRunner | null): IWorld;
  waitForDeployment(): Promise<this>;

  interface: IWorldInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getItemPackNFTs: TypedContractMethod<[], [string[]], "view">;

  getL1NFT: TypedContractMethod<[], [string], "view">;

  setGame: TypedContractMethod<[game_: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getItemPackNFTs"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getL1NFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setGame"
  ): TypedContractMethod<[game_: AddressLike], [void], "nonpayable">;

  filters: {};
}
