"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IItemDefinition__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "itemDefinitionId_",
                type: "uint256",
            },
        ],
        name: "getDefinition",
        outputs: [
            {
                components: [
                    {
                        internalType: "uint256",
                        name: "itemDefinitionId",
                        type: "uint256",
                    },
                    {
                        internalType: "string",
                        name: "category",
                        type: "string",
                    },
                    {
                        internalType: "bool",
                        name: "enable",
                        type: "bool",
                    },
                    {
                        internalType: "bool",
                        name: "salable",
                        type: "bool",
                    },
                    {
                        internalType: "bool",
                        name: "transferable",
                        type: "bool",
                    },
                    {
                        internalType: "uint256",
                        name: "effectivePeriod",
                        type: "uint256",
                    },
                ],
                internalType: "struct IItemDefinition.ItemDefinitionRecord",
                name: "",
                type: "tuple",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                components: [
                    {
                        internalType: "uint256",
                        name: "itemDefinitionId",
                        type: "uint256",
                    },
                    {
                        internalType: "string",
                        name: "category",
                        type: "string",
                    },
                    {
                        internalType: "bool",
                        name: "enable",
                        type: "bool",
                    },
                    {
                        internalType: "bool",
                        name: "salable",
                        type: "bool",
                    },
                    {
                        internalType: "bool",
                        name: "transferable",
                        type: "bool",
                    },
                    {
                        internalType: "uint256",
                        name: "effectivePeriod",
                        type: "uint256",
                    },
                ],
                internalType: "struct IItemDefinition.ItemDefinitionRecord[]",
                name: "records",
                type: "tuple[]",
            },
        ],
        name: "setDefinitions",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class IItemDefinition__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IItemDefinition__factory = IItemDefinition__factory;
IItemDefinition__factory.abi = _abi;
