"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IItemDefinition__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IItemDefinition__factory_1 = require("./IItemDefinition__factory");
Object.defineProperty(exports, "IItemDefinition__factory", { enumerable: true, get: function () { return IItemDefinition__factory_1.IItemDefinition__factory; } });
