/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IL1NFT,
  IL1NFTInterface,
} from "../../../../contracts/interfaces/token/IL1NFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getOwner",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "getTokens",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IL1NFT__factory {
  static readonly abi = _abi;
  static createInterface(): IL1NFTInterface {
    return new utils.Interface(_abi) as IL1NFTInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IL1NFT {
    return new Contract(address, _abi, signerOrProvider) as IL1NFT;
  }
}
