"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IL1NFT__factory = exports.IItemPackNFT__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IItemPackNFT__factory_1 = require("./IItemPackNFT__factory");
Object.defineProperty(exports, "IItemPackNFT__factory", { enumerable: true, get: function () { return IItemPackNFT__factory_1.IItemPackNFT__factory; } });
var IL1NFT__factory_1 = require("./IL1NFT__factory");
Object.defineProperty(exports, "IL1NFT__factory", { enumerable: true, get: function () { return IL1NFT__factory_1.IL1NFT__factory; } });
