/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMintManager,
  IMintManagerInterface,
} from "../../../contracts/token/IMintManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "worldId",
        type: "uint256",
      },
      {
        internalType: "uint64",
        name: "seriesId",
        type: "uint64",
      },
    ],
    name: "getBalanceBySeries",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "worldId",
        type: "uint256",
      },
      {
        internalType: "uint64",
        name: "seriesId",
        type: "uint64",
      },
    ],
    name: "getMintedCountBySeries",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "quantity",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "worldId",
        type: "uint256",
      },
      {
        internalType: "uint64",
        name: "seriesId",
        type: "uint64",
      },
    ],
    name: "mintBySeries",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMintManager__factory {
  static readonly abi = _abi;
  static createInterface(): IMintManagerInterface {
    return new Interface(_abi) as IMintManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMintManager {
    return new Contract(address, _abi, runner) as unknown as IMintManager;
  }
}
